# Generated by Django 3.2.15 on 2022-12-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_topicsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicSearch',
        ),
    ]
