# Generated by Django 3.2.15 on 2022-12-26 19:48

from django.db import migrations, models
import learning_logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_delete_topicsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, validators=[learning_logs.models.validate_non_numeric, learning_logs.models.validate_special_characters]),
        ),
    ]
